### ISSUE TITLE
Possible issue with dependentDomains?

### ISSUE THREAD

**Issue by zehawki** [JohnMealy23/cookie-toss#26]
Doing some local testing:

1. In the hub I've set `const dependentDomains = ["localhost:X"];` (X being some port number).
2. Then I run a satellite on localhost:Y, but find that it can get/set from hub.

Surely this should be prevented, or? Since localhost:Y is not whitelisted.

**Comment by JohnMealy23** [comment]
Hello @zehawki, and sorry for the lag in reply.

This is a good observation - thank you for it.  The module currently only checks for a hostname match between access listings and request origin, and disregards ports.  You can see this happening [here](https://github.com/JohnMealy23/cookie-toss/blob/master/src/iframe/index.ts#L15).  

I've put in [a PR to remedy this](https://github.com/JohnMealy23/cookie-toss/pull/27), and allow for port-level access listing.  [I've also sent you an invite to collaborate](https://github.com/JohnMealy23/cookie-toss/invitations), in case you'd like to be on the PR.

**Comment by JohnMealy23** [comment]
I've merged the PR (06e7803).  Please advise if this does not address the issue.
